### ISSUE TITLE
Not all files being deleted

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jesec/flood#25]
## Your Environment

* Version used: `b310ae`
* Environment name and version:
  + Node.js version v14.9.0
  + npm version 6.14.8

Given a torrent with a file structure as so:
```
Big Buck Bunny
               ├─Big Buck Bunny.en.srt
               ├─Big Buck Bunny.mp4
               └─poster.jpg
```

The files get downloaded successfully, yet when I delete the torrent and select `Delete Data`, everything is deleted except for the folder. (which is included in the torrent

## Steps to Reproduce
Torrent file: https://files.catbox.moe/onw3g1.torrent

1. Add the torrent
1. Wait for torrent to download
1. Delete with `delete data` checked
1. Observe every file gets deleted except for the folder included in the torrent (`Big Buck Bunny`)

**Comment by jesec** [comment]
See https://github.com/jesec/flood/issues/13. 

It is intended that base directory of a torrent is not deleted.

**Comment by ThatNerdyPikachu** [comment]
Ah, alright.

Question: what are the circumstances that the "Use folder as base" option will work? i.e. it doesn't seem plausible that it'd merge several directories i.e.
```
a/
b/
c/
```

so it seems like it'd only be useful for torrents with a single folder inside, unless there's some other use i'm missing.

**Comment by jesec** [comment]
A torrent only has one base directory. It is usually named after the torrent itself. 

Suppose there is a `Downloads` folder and it is the `Download Destination`.

Suppose there is a torrent called A_TORRENT and it has three folders a/, b/ and c/. 

Normally (if you don’t select `use as base`) a folder called A_TORRENT will be created and used as base directory. 

```
Downloads
        ├─ A_TORRENT
                   ├─ a
                   ├─ b
                   ├─ c
```

If you select `use as base`:
```
Downloads
        ├─ a
        ├─ b
        ├─ c
```

**It would be too dangerous to delete base directory because:**

Suppose there is a single file torrent called B_TORRENT and it has only one file `ubuntu_20.04.iso`. In this case, you don't want something like Downloads/B_TORRENT/ubuntu_20.04.iso. Instead you want Downloads/ubuntu_20.04.iso. So base directory is Downloads. And you probably don't really want your `Downloads` to be deleted.

There are also other edge cases when `Move torrent`, `Use as base`, etc. are involved. It is probably better to stay on the safe side when it comes to permanent data removal. 

**There is a `use as base` option because:** 

It allows users to select a folder that has the different name than the torrent. Suppose you think `A_TORRENT` is a poor name and you want the directory to be called `MY_SUPER_ORGANIZED_FOLDER`. Then you use `Downloads/MY_SUPER_ORGANIZED_FOLDER` as `Download Destination` and select `Use as base`. The result:
```
Downloads
        ├─ MY_SUPER_ORGANIZED_FOLDER
                                    ├─ a
                                    ├─ b
                                    ├─ c
```

Practically:
Suppose there are two torrents. They have identical contents but different names. One is `A_TORRENT[tartv]` and the other is `A_TORRENT[ziptv]`. Now for some reasons you want to seed your downloaded contents to swarms of both torrents. You can use `use as base` to ignore the torrent name difference.

**Comment by ThatNerdyPikachu** [comment]
This clears up a lot, thank you.

> A torrent only has one base directory. It is usually named after the torrent itself.

So a torrent either has a base directory or a single file, correct?

**Comment by jesec** [comment]
All torrents have base directory. The difference is that for single file torrents, `Download Destination` is used as base directory. No extra folder will be created.

**Comment by ThatNerdyPikachu** [comment]
Ah, gotcha.

Thank you for your very helpful explanations!
