### ISSUE TITLE
Unable to connect to qBittorrent using Kubernetes service name

### ISSUE THREAD

**Issue by onedr0p** [jesec/flood#95]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

- Version used: v4.1.1
- Operating System and version: Docker image

## Summary

Hi, I am unable to connect flood to qBittorrent using Kubernetes service names. I've tried to connect to these URLs in flood via the following URLs however it won't connect. These domains are internally route-able in my Kubernetes cluster and I can ping / curl the endpoint from other docker containers.

`FLOOD_OPTION_QBURL: "http://qbittorrent:8080/api/v2"`

or

`FLOOD_OPTION_QBURL: "http://qbittorrent.media.svc.cluster.local:8080/api/v2"`

This likely affects other clients as well.

## Expected Behavior

Flood should be able to connect to qbittorrent via a kubernetes service names.

## Current Behavior

Flood is unable to connect to qbittorrent using kubernetes service names.

## Possible Solution

Tracing this issue upstream to the zod library. 
https://github.com/colinhacks/zod/blob/master/src/types/string.ts#L64
https://github.com/colinhacks/zod/blob/master/src/__tests__/string.test.ts#L38

https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

Any string should be considered a valid url if it similar to `/[A-Za-z0-9-.]+/`

## Steps to Reproduce

1. Deploy qbittorrent and flood in containers in a kubernetes cluster
2. Try to use kubernetes service name to connect flood to qbittorrent
3. ??
4. Fail

## Logs

```
GET /static/media/Roboto-italic.766b7c5c.woff2 304 0.586 ms - -
GET /static/media/Roboto-500.c7e17507.woff2 304 0.412 ms - -
GET /static/media/Roboto-700.2b8c7cb1.woff2 304 0.401 ms - -
GET /favicon.ico 200 7.981 ms - -
GET /overview 200 3.400 ms - 604
GET /api/activity-stream?historySnapshot=FIVE_MINUTE 200 2.129 ms - -
GET /static/css/main.2fbe858695bd101d3959.css 304 1.988 ms - -
GET /static/js/main.fbad339e.js 304 0.859 ms - -
GET /static/css/802.508b6bc040707a7791ff.css 304 2.530 ms - -
GET /api/auth/verify?1605846483093 200 1.016 ms - 105
GET /static/js/802.bc733132.chunk.js 304 3.292 ms - -
GET /static/js/93.0d577883.chunk.js 304 2.844 ms - -
GET /api/client/settings 500 0.911 ms - 40
GET /api/settings 200 1.308 ms - 2
GET /static/js/842.0d6478a7.chunk.js 304 5.730 ms - -
GET /static/js/786.2a373c1f.chunk.js 304 4.868 ms - -
GET /static/js/flag2.0b49da8f.chunk.js 304 4.557 ms - -
undefined
```

## Debugging from another container

```
✖ kubectl exec -it pod/jackett-test-747484c4bd-htkvv -n media -- bash
kah@jackett-test-747484c4bd-htkvv:/app$ curl qbittorrent:8080
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>qBittorrent Web UI</title>
```

Thanks for providing this app, it looks like a great UI for a bunch of torrent clients.

**Comment by jesec** [comment]
`--qburl` only works with `--auth=none`. You will see `Starting without builtin authentication` when `auth=none`. 

If you use default authentication method (`auth=default`), you will be prompted to configure the connection to torrent client when loading the web interface. (https://github.com/jesec/flood#configuration)

Additionally, Flood uses `${url}/api/v2` internally so your URL shall not contain `/api/v2` part. 

It is unlikely that the issue is related to the validation library. In case of configuration validation failure, Flood will simply refuse to start. 

Internally Flood uses `axios` , which in turn uses `http.request` of Node.js. Like most programs, Flood does not perform or control name resolution. Docker image of Flood is composed simply via `sudo npm install --global flood` inside the official Node.js alpine image. I think you might want to `/bin/sh` the Flood image and see if there is anything wrong with name resolution.

**Comment by onedr0p** [comment]
> --qburl only works with --auth=none. You will see Starting without builtin authentication when auth=none.

Cool I was doing that part right then :)

> I think you might want to /bin/sh the Flood image and see if there is anything wrong with name resolution.

The Docker image doesn't contain ping or any other networking tools to help :(

> Additionally, Flood uses ${url}/api/v2 internally so your URL shall not contain /api/v2 part.

This was actually the solution to the problem, thanks for correction me on that! Not sure why I thought else wise, I tried searching the code but failed spectacularly :D
